target:
	gfortran zmns.f90 -g -fcheck=all -o debug.exe
	./debug.exe
clean:
	rm *.mod *.txt *.csv *.exe

# target:
# 	gfortran zmns.f90 -g -fcheck=all -o debug.o
# 	./debug.o
# clean:
# 	del *.mod *.txt *.csv *.o